server:
    port: 8098
spring:
  application:
      name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
            enabled: true   
            lower-case-service-id: true  
    consul:
        host: 127.0.0.1 #注册gateway网关到consul
        port: 8500
      discovery:
          service-name: service-gateway