server:
  port: 19000
spring:
  application:
    name: config-server
  security:
    basic:
      enabled: true
    user.name: config
    user.password: 123
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deng-hb/spring-cloud-example.git
          # 配置文件在git仓库的目录
          searchPaths: /config/
          force-pull: true
  # mq 刷新
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # spring boot admin
  boot:
    admin:
      client:
        url: http://admin:123@localhost:9999
eureka:
  client:
    service-url:
      defaultZone: http://eureka:123@localhost:11000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS